instruction_encoding: instruction_encoding_element ("//" instruction_encoding_element)*
instruction_encoding_element: field_encoding ("|" field_encoding)*
field_encoding: field_bits (":" id ("[" field_bit_ranges "]")?)?
field_bits: BIT_ARRAY+
field_bit_ranges: field_bit_range ("," field_bit_range)*
field_bit_range: number (":" number)?
id: ID
number: NUMBER

BIT_ARRAY: /[01x]+/
ID: /[A-Za-z]\w*/
NUMBER: /\d+/

%import common.WS
%ignore WS
